---
title: TIMESPENT
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  videos:
    title: videos
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: videos
  values:
    layout: video
    permalink: "/videos/:title/"
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- gulpfile.js
- node_modules
- package.json
- assets/sass/
